### ISSUE TITLE
Krita 4.3.0 AttributeError: 'NoneType' object has no attribute 'qwindow'

### ISSUE THREAD

**Issue by AnnA-Ayms** [Falano/kritaSpritesheetManager#9]
AttributeError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Fri Jun 19 15:31:54 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\AnnA Ayms\AppData\Roaming\krita\pykrita\spritesheetExporter\spritesheetexporterextension.py in createActions(self=<spritesheetExporter.spritesheetexporterextension.spritesheetExporterExtension object>, window=<PyKrita.krita.Window object>)
   40 
   41         # when you click on the script in the menu it opens the dialog window
   42         self.ui = uispritesheetexporter.UISpritesheetExporter()
   43         exportSs.triggered.connect(self.ui.showExportDialog)
   44 
self = <spritesheetExporter.spritesheetexporterextension.spritesheetExporterExtension object>
self.ui undefined
global uispritesheetexporter = <module 'spritesheetExporter.uispritesheetexport...\\spritesheetExporter\\uispritesheetexporter.py'>
uispritesheetexporter.UISpritesheetExporter = <class 'spritesheetExporter.uispritesheetexporter.UISpritesheetExporter'>

 C:\Users\AnnA Ayms\AppData\Roaming\krita\pykrita\spritesheetExporter\uispritesheetexporter.py in __init__(self=<spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>)
   33 
   34         # the main window
   35         self.mainDialog = QDialog(self.app.activeWindow().qwindow())
   36 
   37         # the window is not modal and does not block input to other windows
self = <spritesheetExporter.uispritesheetexporter.UISpritesheetExporter object>
self.mainDialog undefined
global QDialog = <class 'PyQt5.QtWidgets.QDialog'>
self.app = <PyKrita.krita.Krita object>
self.app.activeWindow = <built-in method activeWindow of Krita object>
).qwindow undefined
AttributeError: 'NoneType' object has no attribute 'qwindow'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'qwindow'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\AnnA Ayms\AppData\Roaming\krita\pykrita\spritesheetExporter\spritesheetexporterextension.py", line 42, in createActions
    self.ui = uispritesheetexporter.UISpritesheetExporter()
  File "C:\Users\AnnA Ayms\AppData\Roaming\krita\pykrita\spritesheetExporter\uispritesheetexporter.py", line 35, in __init__
    self.mainDialog = QDialog(self.app.activeWindow().qwindow())
AttributeError: 'NoneType' object has no attribute 'qwindow'

**Comment by arsvarg** [comment]
I have the same problem.

**Comment by Falano** [comment]
My bad, it slipped my mind. It seems to be a 4.3-only issue, I tested and it works on 4.2.9 and 4.2.1, so probably also in all other 4.2 versions.
I'll look into fixing it.

**Comment by Falano** [comment]
Okay, it should be fixed.

**Comment by AnnA-Ayms** [comment]
It now is working fine in 4.3. Thanks!
